# Generated by Django 5.0 on 2024-02-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rec", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Id_persons",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("person", models.CharField(max_length=100)),
            ],
        ),
    ]
