# Generated by Django 5.0 on 2024-02-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rec", "0002_id_persons"),
    ]

    operations = [
        migrations.RenameField(
            model_name="facerec",
            old_name="person",
            new_name="id_person",
        ),
        migrations.AlterField(
            model_name="id_persons",
            name="id",
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
