# Generated by Django 5.0 on 2024-02-28 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rec", "0003_rename_person_facerec_id_person_alter_id_persons_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="id_persons",
            old_name="id",
            new_name="id_person",
        ),
    ]
